import subprocess


import unittest
import subprocess


class Test(unittest.TestCase):
    def test(self):
        result = subprocess.run(
            [
                "make",
                "-s",
                "build",
            ],
            capture_output=True,
            text=True,
            check=False,
        )

        code = result.returncode
        out = result.stdout.strip()
        err = result.stderr.strip()

        self.assertEqual(code, 0)

        self.assertIn("Hello, world!, header,3,2", out)

        expected_err = """bazel start //bzl:bzl

Namespace(target='//bzl:bzl', debug=True, debug_message_limit=0, args='', shell='/bin/bash', no_build=False)
workspace: /project/main_project
command: bazel build  //bzl:bzl
result: 

command: bazel info  output_base
result: /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a

command: bazel query 'deps(//bzl:bzl)'
result: //bzl:bzl
//bzl:bzl.cpp
//bzl:bzl.hpp
@bazel_tools//src/conditions:host_windows
@bazel_tools//src/conditions:host_windows_arm64_constraint
@bazel_tools//src/conditions:host_windows_x64_constraint
@bazel_tools//src/conditions:remote
@bazel_tools//third_party/def_parser:def_parser
@bazel_tools//third_party/def_parser:def_parser.cc
@bazel_tools//third_party/def_parser:def_parser.h
@bazel_tools//third_party/def_parser:def_parser_lib
@bazel_tools//third_party/def_parser:def_parser_main.cc
@bazel_tools//tools/build_defs/build_info:cc_build_info
@bazel_tools//tools/build_defs/build_info/templates:non_volatile_file.h.template
@bazel_tools//tools/build_defs/build_info/templates:redacted_file.h.template
@bazel_tools//tools/build_defs/build_info/templates:volatile_file.h.template
@bazel_tools//tools/build_defs/cc/whitelists/parse_headers_and_layering_check:disabling_parse_headers_and_layering_check_allowed
@bazel_tools//tools/cpp:build_interface_so
@bazel_tools//tools/cpp:current_cc_toolchain
@bazel_tools//tools/cpp:empty_lib
@bazel_tools//tools/cpp:interface_library_builder
@bazel_tools//tools/cpp:link_dynamic_library
@bazel_tools//tools/cpp:link_dynamic_library.sh
@bazel_tools//tools/cpp:link_extra_lib
@bazel_tools//tools/cpp:link_extra_libs
@bazel_tools//tools/cpp:malloc
@bazel_tools//tools/cpp:toolchain
@bazel_tools//tools/cpp:toolchain_type
@bazel_tools//tools/def_parser:def_parser
@bazel_tools//tools/def_parser:def_parser.exe
@bazel_tools//tools/def_parser:def_parser_windows
@bazel_tools//tools/def_parser:no_op.bat
@bazel_tools//tools/objc:host_xcodes
@@bazel_tools~cc_configure_extension~local_config_cc//:builtin_include_directory_paths
@@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-armeabi-v7a
@@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-k8
@@bazel_tools~cc_configure_extension~local_config_cc//:cc_wrapper
@@bazel_tools~cc_configure_extension~local_config_cc//:cc_wrapper.sh
@@bazel_tools~cc_configure_extension~local_config_cc//:compiler_deps
@@bazel_tools~cc_configure_extension~local_config_cc//:empty
@@bazel_tools~cc_configure_extension~local_config_cc//:local
@@bazel_tools~cc_configure_extension~local_config_cc//:stub_armeabi-v7a
@@bazel_tools~cc_configure_extension~local_config_cc//:toolchain
@@bazel_tools~cc_configure_extension~local_config_cc//:validate_static_library
@@bazel_tools~cc_configure_extension~local_config_cc//:validate_static_library.sh
@@boost.assert~//:boost.assert
@@boost.assert~//:include/boost/assert.hpp
@@boost.assert~//:include/boost/assert/source_location.hpp
@@boost.assert~//:include/boost/current_function.hpp
@@boost.config~//:boost.config
@@boost.config~//:include/boost/config.hpp
@@boost.config~//:include/boost/config/abi/borland_prefix.hpp
@@boost.config~//:include/boost/config/abi/borland_suffix.hpp
@@boost.config~//:include/boost/config/abi/msvc_prefix.hpp
@@boost.config~//:include/boost/config/abi/msvc_suffix.hpp
@@boost.config~//:include/boost/config/abi_prefix.hpp
@@boost.config~//:include/boost/config/abi_suffix.hpp
@@boost.config~//:include/boost/config/assert_cxx03.hpp
@@boost.config~//:include/boost/config/assert_cxx11.hpp
@@boost.config~//:include/boost/config/assert_cxx14.hpp
@@boost.config~//:include/boost/config/assert_cxx17.hpp
@@boost.config~//:include/boost/config/assert_cxx20.hpp
@@boost.config~//:include/boost/config/assert_cxx98.hpp
@@boost.config~//:include/boost/config/auto_link.hpp
@@boost.config~//:include/boost/config/compiler/borland.hpp
@@boost.config~//:include/boost/config/compiler/clang.hpp
@@boost.config~//:include/boost/config/compiler/clang_version.hpp
@@boost.config~//:include/boost/config/compiler/codegear.hpp
@@boost.config~//:include/boost/config/compiler/comeau.hpp
@@boost.config~//:include/boost/config/compiler/common_edg.hpp
@@boost.config~//:include/boost/config/compiler/compaq_cxx.hpp
@@boost.config~//:include/boost/config/compiler/cray.hpp
@@boost.config~//:include/boost/config/compiler/diab.hpp
@@boost.config~//:include/boost/config/compiler/digitalmars.hpp
@@boost.config~//:include/boost/config/compiler/gcc.hpp
@@boost.config~//:include/boost/config/compiler/gcc_xml.hpp
@@boost.config~//:include/boost/config/compiler/greenhills.hpp
@@boost.config~//:include/boost/config/compiler/hp_acc.hpp
@@boost.config~//:include/boost/config/compiler/intel.hpp
@@boost.config~//:include/boost/config/compiler/kai.hpp
@@boost.config~//:include/boost/config/compiler/metrowerks.hpp
@@boost.config~//:include/boost/config/compiler/mpw.hpp
@@boost.config~//:include/boost/config/compiler/nvcc.hpp
@@boost.config~//:include/boost/config/compiler/pathscale.hpp
@@boost.config~//:include/boost/config/compiler/pgi.hpp
@@boost.config~//:include/boost/config/compiler/sgi_mipspro.hpp
@@boost.config~//:include/boost/config/compiler/sunpro_cc.hpp
@@boost.config~//:include/boost/config/compiler/vacpp.hpp
@@boost.config~//:include/boost/config/compiler/visualc.hpp
@@boost.config~//:include/boost/config/compiler/xlcpp.hpp
@@boost.config~//:include/boost/config/compiler/xlcpp_zos.hpp
@@boost.config~//:include/boost/config/detail/cxx_composite.hpp
@@boost.config~//:include/boost/config/detail/posix_features.hpp
@@boost.config~//:include/boost/config/detail/select_compiler_config.hpp
@@boost.config~//:include/boost/config/detail/select_platform_config.hpp
@@boost.config~//:include/boost/config/detail/select_stdlib_config.hpp
@@boost.config~//:include/boost/config/detail/suffix.hpp
@@boost.config~//:include/boost/config/header_deprecated.hpp
@@boost.config~//:include/boost/config/helper_macros.hpp
@@boost.config~//:include/boost/config/no_tr1/cmath.hpp
@@boost.config~//:include/boost/config/no_tr1/complex.hpp
@@boost.config~//:include/boost/config/no_tr1/functional.hpp
@@boost.config~//:include/boost/config/no_tr1/memory.hpp
@@boost.config~//:include/boost/config/no_tr1/utility.hpp
@@boost.config~//:include/boost/config/platform/aix.hpp
@@boost.config~//:include/boost/config/platform/amigaos.hpp
@@boost.config~//:include/boost/config/platform/beos.hpp
@@boost.config~//:include/boost/config/platform/bsd.hpp
@@boost.config~//:include/boost/config/platform/cloudabi.hpp
@@boost.config~//:include/boost/config/platform/cray.hpp
@@boost.config~//:include/boost/config/platform/cygwin.hpp
@@boost.config~//:include/boost/config/platform/haiku.hpp
@@boost.config~//:include/boost/config/platform/hpux.hpp
@@boost.config~//:include/boost/config/platform/irix.hpp
@@boost.config~//:include/boost/config/platform/linux.hpp
@@boost.config~//:include/boost/config/platform/macos.hpp
@@boost.config~//:include/boost/config/platform/qnxnto.hpp
@@boost.config~//:include/boost/config/platform/solaris.hpp
@@boost.config~//:include/boost/config/platform/symbian.hpp
@@boost.config~//:include/boost/config/platform/vms.hpp
@@boost.config~//:include/boost/config/platform/vxworks.hpp
@@boost.config~//:include/boost/config/platform/wasm.hpp
@@boost.config~//:include/boost/config/platform/win32.hpp
@@boost.config~//:include/boost/config/platform/zos.hpp
@@boost.config~//:include/boost/config/pragma_message.hpp
@@boost.config~//:include/boost/config/requires_threads.hpp
@@boost.config~//:include/boost/config/stdlib/dinkumware.hpp
@@boost.config~//:include/boost/config/stdlib/libcomo.hpp
@@boost.config~//:include/boost/config/stdlib/libcpp.hpp
@@boost.config~//:include/boost/config/stdlib/libstdcpp3.hpp
@@boost.config~//:include/boost/config/stdlib/modena.hpp
@@boost.config~//:include/boost/config/stdlib/msl.hpp
@@boost.config~//:include/boost/config/stdlib/roguewave.hpp
@@boost.config~//:include/boost/config/stdlib/sgi.hpp
@@boost.config~//:include/boost/config/stdlib/stlport.hpp
@@boost.config~//:include/boost/config/stdlib/vacpp.hpp
@@boost.config~//:include/boost/config/stdlib/xlcpp_zos.hpp
@@boost.config~//:include/boost/config/user.hpp
@@boost.config~//:include/boost/config/warning_disable.hpp
@@boost.config~//:include/boost/config/workaround.hpp
@@boost.config~//:include/boost/cstdint.hpp
@@boost.config~//:include/boost/cxx11_char_types.hpp
@@boost.config~//:include/boost/detail/workaround.hpp
@@boost.config~//:include/boost/limits.hpp
@@boost.config~//:include/boost/version.hpp
@@boost.container_hash~//:boost.container_hash
@@boost.container_hash~//:include/boost/container_hash/detail/hash_mix.hpp
@@boost.container_hash~//:include/boost/container_hash/detail/hash_range.hpp
@@boost.container_hash~//:include/boost/container_hash/detail/hash_tuple_like.hpp
@@boost.container_hash~//:include/boost/container_hash/detail/limits.hpp
@@boost.container_hash~//:include/boost/container_hash/detail/mulx.hpp
@@boost.container_hash~//:include/boost/container_hash/detail/requires_cxx11.hpp
@@boost.container_hash~//:include/boost/container_hash/extensions.hpp
@@boost.container_hash~//:include/boost/container_hash/hash.hpp
@@boost.container_hash~//:include/boost/container_hash/hash_fwd.hpp
@@boost.container_hash~//:include/boost/container_hash/is_contiguous_range.hpp
@@boost.container_hash~//:include/boost/container_hash/is_described_class.hpp
@@boost.container_hash~//:include/boost/container_hash/is_range.hpp
@@boost.container_hash~//:include/boost/container_hash/is_tuple_like.hpp
@@boost.container_hash~//:include/boost/container_hash/is_unordered_range.hpp
@@boost.container_hash~//:include/boost/functional/hash.hpp
@@boost.container_hash~//:include/boost/functional/hash/extensions.hpp
@@boost.container_hash~//:include/boost/functional/hash/hash.hpp
@@boost.container_hash~//:include/boost/functional/hash/hash_fwd.hpp
@@boost.container_hash~//:include/boost/functional/hash_fwd.hpp
@boost.container//:boost.container
@boost.container//:include/boost/container/adaptive_pool.hpp
@boost.container//:include/boost/container/allocator.hpp
@boost.container//:include/boost/container/allocator_traits.hpp
@boost.container//:include/boost/container/container_fwd.hpp
@boost.container//:include/boost/container/deque.hpp
@boost.container//:include/boost/container/detail/adaptive_node_pool.hpp
@boost.container//:include/boost/container/detail/adaptive_node_pool_impl.hpp
@boost.container//:include/boost/container/detail/addressof.hpp
@boost.container//:include/boost/container/detail/advanced_insert_int.hpp
@boost.container//:include/boost/container/detail/algorithm.hpp
@boost.container//:include/boost/container/detail/alloc_helpers.hpp
@boost.container//:include/boost/container/detail/alloc_lib.h
@boost.container//:include/boost/container/detail/allocation_type.hpp
@boost.container//:include/boost/container/detail/allocator_version_traits.hpp
@boost.container//:include/boost/container/detail/auto_link.hpp
@boost.container//:include/boost/container/detail/block_list.hpp
@boost.container//:include/boost/container/detail/block_slist.hpp
@boost.container//:include/boost/container/detail/compare_functors.hpp
@boost.container//:include/boost/container/detail/config_begin.hpp
@boost.container//:include/boost/container/detail/config_end.hpp
@boost.container//:include/boost/container/detail/construct_in_place.hpp
@boost.container//:include/boost/container/detail/container_or_allocator_rebind.hpp
@boost.container//:include/boost/container/detail/container_rebind.hpp
@boost.container//:include/boost/container/detail/copy_move_algo.hpp
@boost.container//:include/boost/container/detail/destroyers.hpp
@boost.container//:include/boost/container/detail/dispatch_uses_allocator.hpp
@boost.container//:include/boost/container/detail/dlmalloc.hpp
@boost.container//:include/boost/container/detail/flat_tree.hpp
@boost.container//:include/boost/container/detail/function_detector.hpp
@boost.container//:include/boost/container/detail/guards_dended.hpp
@boost.container//:include/boost/container/detail/is_container.hpp
@boost.container//:include/boost/container/detail/is_contiguous_container.hpp
@boost.container//:include/boost/container/detail/is_pair.hpp
@boost.container//:include/boost/container/detail/is_sorted.hpp
@boost.container//:include/boost/container/detail/iterator.hpp
@boost.container//:include/boost/container/detail/iterator_to_raw_pointer.hpp
@boost.container//:include/boost/container/detail/iterators.hpp
@boost.container//:include/boost/container/detail/math_functions.hpp
@boost.container//:include/boost/container/detail/min_max.hpp
@boost.container//:include/boost/container/detail/minimal_char_traits_header.hpp
@boost.container//:include/boost/container/detail/mpl.hpp
@boost.container//:include/boost/container/detail/multiallocation_chain.hpp
@boost.container//:include/boost/container/detail/mutex.hpp
@boost.container//:include/boost/container/detail/next_capacity.hpp
@boost.container//:include/boost/container/detail/node_alloc_holder.hpp
@boost.container//:include/boost/container/detail/node_pool.hpp
@boost.container//:include/boost/container/detail/node_pool_impl.hpp
@boost.container//:include/boost/container/detail/pair.hpp
@boost.container//:include/boost/container/detail/pair_key_mapped_of_value.hpp
@boost.container//:include/boost/container/detail/placement_new.hpp
@boost.container//:include/boost/container/detail/pool_common.hpp
@boost.container//:include/boost/container/detail/pool_common_alloc.hpp
@boost.container//:include/boost/container/detail/pool_resource.hpp
@boost.container//:include/boost/container/detail/singleton.hpp
@boost.container//:include/boost/container/detail/std_fwd.hpp
@boost.container//:include/boost/container/detail/thread_mutex.hpp
@boost.container//:include/boost/container/detail/transform_iterator.hpp
@boost.container//:include/boost/container/detail/tree.hpp
@boost.container//:include/boost/container/detail/type_traits.hpp
@boost.container//:include/boost/container/detail/value_functors.hpp
@boost.container//:include/boost/container/detail/value_init.hpp
@boost.container//:include/boost/container/detail/variadic_templates_tools.hpp
@boost.container//:include/boost/container/detail/version_type.hpp
@boost.container//:include/boost/container/detail/workaround.hpp
@boost.container//:include/boost/container/devector.hpp
@boost.container//:include/boost/container/flat_map.hpp
@boost.container//:include/boost/container/flat_set.hpp
@boost.container//:include/boost/container/list.hpp
@boost.container//:include/boost/container/map.hpp
@boost.container//:include/boost/container/new_allocator.hpp
@boost.container//:include/boost/container/node_allocator.hpp
@boost.container//:include/boost/container/node_handle.hpp
@boost.container//:include/boost/container/options.hpp
@boost.container//:include/boost/container/pmr/deque.hpp
@boost.container//:include/boost/container/pmr/devector.hpp
@boost.container//:include/boost/container/pmr/flat_map.hpp
@boost.container//:include/boost/container/pmr/flat_set.hpp
@boost.container//:include/boost/container/pmr/global_resource.hpp
@boost.container//:include/boost/container/pmr/list.hpp
@boost.container//:include/boost/container/pmr/map.hpp
@boost.container//:include/boost/container/pmr/memory_resource.hpp
@boost.container//:include/boost/container/pmr/monotonic_buffer_resource.hpp
@boost.container//:include/boost/container/pmr/polymorphic_allocator.hpp
@boost.container//:include/boost/container/pmr/pool_options.hpp
@boost.container//:include/boost/container/pmr/resource_adaptor.hpp
@boost.container//:include/boost/container/pmr/set.hpp
@boost.container//:include/boost/container/pmr/slist.hpp
@boost.container//:include/boost/container/pmr/small_vector.hpp
@boost.container//:include/boost/container/pmr/stable_vector.hpp
@boost.container//:include/boost/container/pmr/string.hpp
@boost.container//:include/boost/container/pmr/synchronized_pool_resource.hpp
@boost.container//:include/boost/container/pmr/unsynchronized_pool_resource.hpp
@boost.container//:include/boost/container/pmr/vector.hpp
@boost.container//:include/boost/container/scoped_allocator.hpp
@boost.container//:include/boost/container/scoped_allocator_fwd.hpp
@boost.container//:include/boost/container/set.hpp
@boost.container//:include/boost/container/slist.hpp
@boost.container//:include/boost/container/small_vector.hpp
@boost.container//:include/boost/container/stable_vector.hpp
@boost.container//:include/boost/container/static_vector.hpp
@boost.container//:include/boost/container/string.hpp
@boost.container//:include/boost/container/throw_exception.hpp
@boost.container//:include/boost/container/uses_allocator.hpp
@boost.container//:include/boost/container/uses_allocator_fwd.hpp
@boost.container//:include/boost/container/vector.hpp
@@boost.describe~//:boost.describe
@@boost.describe~//:include/boost/describe.hpp
@@boost.describe~//:include/boost/describe/bases.hpp
@@boost.describe~//:include/boost/describe/class.hpp
@@boost.describe~//:include/boost/describe/descriptor_by_name.hpp
@@boost.describe~//:include/boost/describe/descriptor_by_pointer.hpp
@@boost.describe~//:include/boost/describe/detail/bases.hpp
@@boost.describe~//:include/boost/describe/detail/compute_base_modifiers.hpp
@@boost.describe~//:include/boost/describe/detail/config.hpp
@@boost.describe~//:include/boost/describe/detail/cx_streq.hpp
@@boost.describe~//:include/boost/describe/detail/list.hpp
@@boost.describe~//:include/boost/describe/detail/members.hpp
@@boost.describe~//:include/boost/describe/detail/pp_for_each.hpp
@@boost.describe~//:include/boost/describe/detail/pp_utilities.hpp
@@boost.describe~//:include/boost/describe/detail/void_t.hpp
@@boost.describe~//:include/boost/describe/enum.hpp
@@boost.describe~//:include/boost/describe/enum_from_string.hpp
@@boost.describe~//:include/boost/describe/enum_to_string.hpp
@@boost.describe~//:include/boost/describe/enumerators.hpp
@@boost.describe~//:include/boost/describe/members.hpp
@@boost.describe~//:include/boost/describe/modifier_description.hpp
@@boost.describe~//:include/boost/describe/modifiers.hpp
@@boost.describe~//:include/boost/describe/operators.hpp
@@boost.intrusive~//:boost.intrusive
@@boost.intrusive~//:include/boost/intrusive/any_hook.hpp
@@boost.intrusive~//:include/boost/intrusive/avl_set.hpp
@@boost.intrusive~//:include/boost/intrusive/avl_set_hook.hpp
@@boost.intrusive~//:include/boost/intrusive/avltree.hpp
@@boost.intrusive~//:include/boost/intrusive/avltree_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/bs_set.hpp
@@boost.intrusive~//:include/boost/intrusive/bs_set_hook.hpp
@@boost.intrusive~//:include/boost/intrusive/bstree.hpp
@@boost.intrusive~//:include/boost/intrusive/bstree_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/circular_list_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/circular_slist_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/derivation_value_traits.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/algo_type.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/algorithm.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/any_node_and_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/array_initializer.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/assert.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/avltree_node.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/bstree_algorithms_base.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/common_slist_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/config_begin.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/config_end.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/default_header_holder.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/ebo_functor_holder.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/empty_node_checker.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/equal_to_value.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/exception_disposer.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/function_detector.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/generic_hook.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/get_value_traits.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/has_member_function_callable_with.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/hash_combine.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/hashtable_node.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/hook_traits.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/iiterator.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/is_stateful_value_traits.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/iterator.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/key_nodeptr_comp.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/list_iterator.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/list_node.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/math.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/minimal_less_equal_header.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/minimal_pair_header.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/mpl.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/node_cloner_disposer.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/node_holder.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/node_to_value.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/parent_from_member.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/rbtree_node.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/reverse_iterator.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/simple_disposers.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/size_holder.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/slist_iterator.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/slist_node.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/std_fwd.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/transform_iterator.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/tree_iterator.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/tree_node.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/tree_value_compare.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/twin.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/uncast.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/value_functors.hpp
@@boost.intrusive~//:include/boost/intrusive/detail/workaround.hpp
@@boost.intrusive~//:include/boost/intrusive/hashtable.hpp
@@boost.intrusive~//:include/boost/intrusive/intrusive_fwd.hpp
@@boost.intrusive~//:include/boost/intrusive/linear_slist_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/link_mode.hpp
@@boost.intrusive~//:include/boost/intrusive/list.hpp
@@boost.intrusive~//:include/boost/intrusive/list_hook.hpp
@@boost.intrusive~//:include/boost/intrusive/member_value_traits.hpp
@@boost.intrusive~//:include/boost/intrusive/options.hpp
@@boost.intrusive~//:include/boost/intrusive/pack_options.hpp
@@boost.intrusive~//:include/boost/intrusive/parent_from_member.hpp
@@boost.intrusive~//:include/boost/intrusive/pointer_plus_bits.hpp
@@boost.intrusive~//:include/boost/intrusive/pointer_rebind.hpp
@@boost.intrusive~//:include/boost/intrusive/pointer_traits.hpp
@@boost.intrusive~//:include/boost/intrusive/priority_compare.hpp
@@boost.intrusive~//:include/boost/intrusive/rbtree.hpp
@@boost.intrusive~//:include/boost/intrusive/rbtree_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/set.hpp
@@boost.intrusive~//:include/boost/intrusive/set_hook.hpp
@@boost.intrusive~//:include/boost/intrusive/sg_set.hpp
@@boost.intrusive~//:include/boost/intrusive/sgtree.hpp
@@boost.intrusive~//:include/boost/intrusive/sgtree_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/slist.hpp
@@boost.intrusive~//:include/boost/intrusive/slist_hook.hpp
@@boost.intrusive~//:include/boost/intrusive/splay_set.hpp
@@boost.intrusive~//:include/boost/intrusive/splaytree.hpp
@@boost.intrusive~//:include/boost/intrusive/splaytree_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/treap.hpp
@@boost.intrusive~//:include/boost/intrusive/treap_algorithms.hpp
@@boost.intrusive~//:include/boost/intrusive/treap_set.hpp
@@boost.intrusive~//:include/boost/intrusive/trivial_value_traits.hpp
@@boost.intrusive~//:include/boost/intrusive/unordered_set.hpp
@@boost.intrusive~//:include/boost/intrusive/unordered_set_hook.hpp
@@boost.move~//:boost.move
@@boost.move~//:include/boost/move/adl_move_swap.hpp
@@boost.move~//:include/boost/move/algo/adaptive_merge.hpp
@@boost.move~//:include/boost/move/algo/adaptive_sort.hpp
@@boost.move~//:include/boost/move/algo/detail/adaptive_sort_merge.hpp
@@boost.move~//:include/boost/move/algo/detail/basic_op.hpp
@@boost.move~//:include/boost/move/algo/detail/heap_sort.hpp
@@boost.move~//:include/boost/move/algo/detail/insertion_sort.hpp
@@boost.move~//:include/boost/move/algo/detail/is_sorted.hpp
@@boost.move~//:include/boost/move/algo/detail/merge.hpp
@@boost.move~//:include/boost/move/algo/detail/merge_sort.hpp
@@boost.move~//:include/boost/move/algo/detail/pdqsort.hpp
@@boost.move~//:include/boost/move/algo/detail/search.hpp
@@boost.move~//:include/boost/move/algo/detail/set_difference.hpp
@@boost.move~//:include/boost/move/algo/move.hpp
@@boost.move~//:include/boost/move/algo/predicate.hpp
@@boost.move~//:include/boost/move/algo/unique.hpp
@@boost.move~//:include/boost/move/algorithm.hpp
@@boost.move~//:include/boost/move/core.hpp
@@boost.move~//:include/boost/move/default_delete.hpp
@@boost.move~//:include/boost/move/detail/addressof.hpp
@@boost.move~//:include/boost/move/detail/config_begin.hpp
@@boost.move~//:include/boost/move/detail/config_end.hpp
@@boost.move~//:include/boost/move/detail/destruct_n.hpp
@@boost.move~//:include/boost/move/detail/force_ptr.hpp
@@boost.move~//:include/boost/move/detail/fwd_macros.hpp
@@boost.move~//:include/boost/move/detail/iterator_to_raw_pointer.hpp
@@boost.move~//:include/boost/move/detail/iterator_traits.hpp
@@boost.move~//:include/boost/move/detail/meta_utils.hpp
@@boost.move~//:include/boost/move/detail/meta_utils_core.hpp
@@boost.move~//:include/boost/move/detail/move_helpers.hpp
@@boost.move~//:include/boost/move/detail/nsec_clock.hpp
@@boost.move~//:include/boost/move/detail/placement_new.hpp
@@boost.move~//:include/boost/move/detail/pointer_element.hpp
@@boost.move~//:include/boost/move/detail/reverse_iterator.hpp
@@boost.move~//:include/boost/move/detail/std_ns_begin.hpp
@@boost.move~//:include/boost/move/detail/std_ns_end.hpp
@@boost.move~//:include/boost/move/detail/to_raw_pointer.hpp
@@boost.move~//:include/boost/move/detail/type_traits.hpp
@@boost.move~//:include/boost/move/detail/unique_ptr_meta_utils.hpp
@@boost.move~//:include/boost/move/detail/workaround.hpp
@@boost.move~//:include/boost/move/iterator.hpp
@@boost.move~//:include/boost/move/make_unique.hpp
@@boost.move~//:include/boost/move/move.hpp
@@boost.move~//:include/boost/move/traits.hpp
@@boost.move~//:include/boost/move/unique_ptr.hpp
@@boost.move~//:include/boost/move/utility.hpp
@@boost.move~//:include/boost/move/utility_core.hpp
@@boost.mp11~//:boost.mp11
@@boost.mp11~//:include/boost/mp11.hpp
@@boost.mp11~//:include/boost/mp11/algorithm.hpp
@@boost.mp11~//:include/boost/mp11/bind.hpp
@@boost.mp11~//:include/boost/mp11/detail/config.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_append.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_copy_if.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_count.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_defer.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_fold.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_front.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_is_list.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_is_value_list.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_list.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_list_v.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_map_find.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_min_element.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_plus.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_remove_if.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_rename.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_value.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_void.hpp
@@boost.mp11~//:include/boost/mp11/detail/mp_with_index.hpp
@@boost.mp11~//:include/boost/mp11/detail/mpl_common.hpp
@@boost.mp11~//:include/boost/mp11/function.hpp
@@boost.mp11~//:include/boost/mp11/integer_sequence.hpp
@@boost.mp11~//:include/boost/mp11/integral.hpp
@@boost.mp11~//:include/boost/mp11/list.hpp
@@boost.mp11~//:include/boost/mp11/map.hpp
@@boost.mp11~//:include/boost/mp11/mpl.hpp
@@boost.mp11~//:include/boost/mp11/mpl_list.hpp
@@boost.mp11~//:include/boost/mp11/mpl_tuple.hpp
@@boost.mp11~//:include/boost/mp11/set.hpp
@@boost.mp11~//:include/boost/mp11/tuple.hpp
@@boost.mp11~//:include/boost/mp11/utility.hpp
@@boost.mp11~//:include/boost/mp11/version.hpp
@@boost.static_assert~//:boost.static_assert
@@boost.static_assert~//:include/boost/static_assert.hpp
@@boost.type_traits~//:boost.type_traits
@@boost.type_traits~//:include/boost/aligned_storage.hpp
@@boost.type_traits~//:include/boost/type_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/add_const.hpp
@@boost.type_traits~//:include/boost/type_traits/add_cv.hpp
@@boost.type_traits~//:include/boost/type_traits/add_lvalue_reference.hpp
@@boost.type_traits~//:include/boost/type_traits/add_pointer.hpp
@@boost.type_traits~//:include/boost/type_traits/add_reference.hpp
@@boost.type_traits~//:include/boost/type_traits/add_rvalue_reference.hpp
@@boost.type_traits~//:include/boost/type_traits/add_volatile.hpp
@@boost.type_traits~//:include/boost/type_traits/aligned_storage.hpp
@@boost.type_traits~//:include/boost/type_traits/alignment_of.hpp
@@boost.type_traits~//:include/boost/type_traits/alignment_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/arithmetic_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/array_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/broken_compiler_spec.hpp
@@boost.type_traits~//:include/boost/type_traits/common_type.hpp
@@boost.type_traits~//:include/boost/type_traits/composite_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/conditional.hpp
@@boost.type_traits~//:include/boost/type_traits/config.hpp
@@boost.type_traits~//:include/boost/type_traits/conjunction.hpp
@@boost.type_traits~//:include/boost/type_traits/conversion_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/copy_cv.hpp
@@boost.type_traits~//:include/boost/type_traits/copy_cv_ref.hpp
@@boost.type_traits~//:include/boost/type_traits/copy_reference.hpp
@@boost.type_traits~//:include/boost/type_traits/cv_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/decay.hpp
@@boost.type_traits~//:include/boost/type_traits/declval.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/bool_trait_def.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/bool_trait_undef.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/common_arithmetic_type.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/common_type_impl.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/composite_member_pointer_type.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/composite_pointer_type.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/config.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/detector.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/has_binary_operator.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/has_postfix_operator.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/has_prefix_operator.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/ice_and.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/ice_eq.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/ice_not.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/ice_or.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_function_cxx_03.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_function_cxx_11.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_function_msvc10_fix.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_function_ptr_helper.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_function_ptr_tester.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_likely_lambda.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_mem_fun_pointer_impl.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_mem_fun_pointer_tester.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_member_function_pointer_cxx_03.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_member_function_pointer_cxx_11.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_rvalue_reference_msvc10_fix.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/is_swappable_cxx_11.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/mp_defer.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/template_arity_spec.hpp
@@boost.type_traits~//:include/boost/type_traits/detail/yes_no_type.hpp
@@boost.type_traits~//:include/boost/type_traits/detected.hpp
@@boost.type_traits~//:include/boost/type_traits/detected_or.hpp
@@boost.type_traits~//:include/boost/type_traits/disjunction.hpp
@@boost.type_traits~//:include/boost/type_traits/enable_if.hpp
@@boost.type_traits~//:include/boost/type_traits/extent.hpp
@@boost.type_traits~//:include/boost/type_traits/floating_point_promotion.hpp
@@boost.type_traits~//:include/boost/type_traits/function_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/has_bit_and.hpp
@@boost.type_traits~//:include/boost/type_traits/has_bit_and_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_bit_or.hpp
@@boost.type_traits~//:include/boost/type_traits/has_bit_or_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_bit_xor.hpp
@@boost.type_traits~//:include/boost/type_traits/has_bit_xor_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_complement.hpp
@@boost.type_traits~//:include/boost/type_traits/has_dereference.hpp
@@boost.type_traits~//:include/boost/type_traits/has_divides.hpp
@@boost.type_traits~//:include/boost/type_traits/has_divides_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_equal_to.hpp
@@boost.type_traits~//:include/boost/type_traits/has_greater.hpp
@@boost.type_traits~//:include/boost/type_traits/has_greater_equal.hpp
@@boost.type_traits~//:include/boost/type_traits/has_left_shift.hpp
@@boost.type_traits~//:include/boost/type_traits/has_left_shift_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_less.hpp
@@boost.type_traits~//:include/boost/type_traits/has_less_equal.hpp
@@boost.type_traits~//:include/boost/type_traits/has_logical_and.hpp
@@boost.type_traits~//:include/boost/type_traits/has_logical_not.hpp
@@boost.type_traits~//:include/boost/type_traits/has_logical_or.hpp
@@boost.type_traits~//:include/boost/type_traits/has_minus.hpp
@@boost.type_traits~//:include/boost/type_traits/has_minus_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_modulus.hpp
@@boost.type_traits~//:include/boost/type_traits/has_modulus_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_multiplies.hpp
@@boost.type_traits~//:include/boost/type_traits/has_multiplies_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_negate.hpp
@@boost.type_traits~//:include/boost/type_traits/has_new_operator.hpp
@@boost.type_traits~//:include/boost/type_traits/has_not_equal_to.hpp
@@boost.type_traits~//:include/boost/type_traits/has_nothrow_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_nothrow_constructor.hpp
@@boost.type_traits~//:include/boost/type_traits/has_nothrow_copy.hpp
@@boost.type_traits~//:include/boost/type_traits/has_nothrow_destructor.hpp
@@boost.type_traits~//:include/boost/type_traits/has_operator.hpp
@@boost.type_traits~//:include/boost/type_traits/has_plus.hpp
@@boost.type_traits~//:include/boost/type_traits/has_plus_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_post_decrement.hpp
@@boost.type_traits~//:include/boost/type_traits/has_post_increment.hpp
@@boost.type_traits~//:include/boost/type_traits/has_pre_decrement.hpp
@@boost.type_traits~//:include/boost/type_traits/has_pre_increment.hpp
@@boost.type_traits~//:include/boost/type_traits/has_right_shift.hpp
@@boost.type_traits~//:include/boost/type_traits/has_right_shift_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_trivial_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_trivial_constructor.hpp
@@boost.type_traits~//:include/boost/type_traits/has_trivial_copy.hpp
@@boost.type_traits~//:include/boost/type_traits/has_trivial_destructor.hpp
@@boost.type_traits~//:include/boost/type_traits/has_trivial_move_assign.hpp
@@boost.type_traits~//:include/boost/type_traits/has_trivial_move_constructor.hpp
@@boost.type_traits~//:include/boost/type_traits/has_unary_minus.hpp
@@boost.type_traits~//:include/boost/type_traits/has_unary_plus.hpp
@@boost.type_traits~//:include/boost/type_traits/has_virtual_destructor.hpp
@@boost.type_traits~//:include/boost/type_traits/ice.hpp
@@boost.type_traits~//:include/boost/type_traits/integral_constant.hpp
@@boost.type_traits~//:include/boost/type_traits/integral_promotion.hpp
@@boost.type_traits~//:include/boost/type_traits/intrinsics.hpp
@@boost.type_traits~//:include/boost/type_traits/is_abstract.hpp
@@boost.type_traits~//:include/boost/type_traits/is_arithmetic.hpp
@@boost.type_traits~//:include/boost/type_traits/is_array.hpp
@@boost.type_traits~//:include/boost/type_traits/is_assignable.hpp
@@boost.type_traits~//:include/boost/type_traits/is_base_and_derived.hpp
@@boost.type_traits~//:include/boost/type_traits/is_base_of.hpp
@@boost.type_traits~//:include/boost/type_traits/is_base_of_tr1.hpp
@@boost.type_traits~//:include/boost/type_traits/is_bounded_array.hpp
@@boost.type_traits~//:include/boost/type_traits/is_class.hpp
@@boost.type_traits~//:include/boost/type_traits/is_complete.hpp
@@boost.type_traits~//:include/boost/type_traits/is_complex.hpp
@@boost.type_traits~//:include/boost/type_traits/is_compound.hpp
@@boost.type_traits~//:include/boost/type_traits/is_const.hpp
@@boost.type_traits~//:include/boost/type_traits/is_constructible.hpp
@@boost.type_traits~//:include/boost/type_traits/is_convertible.hpp
@@boost.type_traits~//:include/boost/type_traits/is_copy_assignable.hpp
@@boost.type_traits~//:include/boost/type_traits/is_copy_constructible.hpp
@@boost.type_traits~//:include/boost/type_traits/is_default_constructible.hpp
@@boost.type_traits~//:include/boost/type_traits/is_destructible.hpp
@@boost.type_traits~//:include/boost/type_traits/is_detected.hpp
@@boost.type_traits~//:include/boost/type_traits/is_detected_convertible.hpp
@@boost.type_traits~//:include/boost/type_traits/is_detected_exact.hpp
@@boost.type_traits~//:include/boost/type_traits/is_empty.hpp
@@boost.type_traits~//:include/boost/type_traits/is_enum.hpp
@@boost.type_traits~//:include/boost/type_traits/is_final.hpp
@@boost.type_traits~//:include/boost/type_traits/is_float.hpp
@@boost.type_traits~//:include/boost/type_traits/is_floating_point.hpp
@@boost.type_traits~//:include/boost/type_traits/is_function.hpp
@@boost.type_traits~//:include/boost/type_traits/is_fundamental.hpp
@@boost.type_traits~//:include/boost/type_traits/is_integral.hpp
@@boost.type_traits~//:include/boost/type_traits/is_list_constructible.hpp
@@boost.type_traits~//:include/boost/type_traits/is_lvalue_reference.hpp
@@boost.type_traits~//:include/boost/type_traits/is_member_function_pointer.hpp
@@boost.type_traits~//:include/boost/type_traits/is_member_object_pointer.hpp
@@boost.type_traits~//:include/boost/type_traits/is_member_pointer.hpp
@@boost.type_traits~//:include/boost/type_traits/is_noncopyable.hpp
@@boost.type_traits~//:include/boost/type_traits/is_nothrow_move_assignable.hpp
@@boost.type_traits~//:include/boost/type_traits/is_nothrow_move_constructible.hpp
@@boost.type_traits~//:include/boost/type_traits/is_nothrow_swappable.hpp
@@boost.type_traits~//:include/boost/type_traits/is_object.hpp
@@boost.type_traits~//:include/boost/type_traits/is_pod.hpp
@@boost.type_traits~//:include/boost/type_traits/is_pointer.hpp
@@boost.type_traits~//:include/boost/type_traits/is_polymorphic.hpp
@@boost.type_traits~//:include/boost/type_traits/is_reference.hpp
@@boost.type_traits~//:include/boost/type_traits/is_rvalue_reference.hpp
@@boost.type_traits~//:include/boost/type_traits/is_same.hpp
@@boost.type_traits~//:include/boost/type_traits/is_scalar.hpp
@@boost.type_traits~//:include/boost/type_traits/is_scoped_enum.hpp
@@boost.type_traits~//:include/boost/type_traits/is_signed.hpp
@@boost.type_traits~//:include/boost/type_traits/is_stateless.hpp
@@boost.type_traits~//:include/boost/type_traits/is_swappable.hpp
@@boost.type_traits~//:include/boost/type_traits/is_trivially_copyable.hpp
@@boost.type_traits~//:include/boost/type_traits/is_unbounded_array.hpp
@@boost.type_traits~//:include/boost/type_traits/is_union.hpp
@@boost.type_traits~//:include/boost/type_traits/is_unscoped_enum.hpp
@@boost.type_traits~//:include/boost/type_traits/is_unsigned.hpp
@@boost.type_traits~//:include/boost/type_traits/is_virtual_base_of.hpp
@@boost.type_traits~//:include/boost/type_traits/is_void.hpp
@@boost.type_traits~//:include/boost/type_traits/is_volatile.hpp
@@boost.type_traits~//:include/boost/type_traits/make_signed.hpp
@@boost.type_traits~//:include/boost/type_traits/make_unsigned.hpp
@@boost.type_traits~//:include/boost/type_traits/make_void.hpp
@@boost.type_traits~//:include/boost/type_traits/negation.hpp
@@boost.type_traits~//:include/boost/type_traits/nonesuch.hpp
@@boost.type_traits~//:include/boost/type_traits/object_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/promote.hpp
@@boost.type_traits~//:include/boost/type_traits/rank.hpp
@@boost.type_traits~//:include/boost/type_traits/reference_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/remove_all_extents.hpp
@@boost.type_traits~//:include/boost/type_traits/remove_bounds.hpp
@@boost.type_traits~//:include/boost/type_traits/remove_const.hpp
@@boost.type_traits~//:include/boost/type_traits/remove_cv.hpp
@@boost.type_traits~//:include/boost/type_traits/remove_cv_ref.hpp
@@boost.type_traits~//:include/boost/type_traits/remove_extent.hpp
@@boost.type_traits~//:include/boost/type_traits/remove_pointer.hpp
@@boost.type_traits~//:include/boost/type_traits/remove_reference.hpp
@@boost.type_traits~//:include/boost/type_traits/remove_volatile.hpp
@@boost.type_traits~//:include/boost/type_traits/same_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/transform_traits.hpp
@@boost.type_traits~//:include/boost/type_traits/type_identity.hpp
@@boost.type_traits~//:include/boost/type_traits/type_with_alignment.hpp
@@boost.type_traits~//:include/boost/utility/declval.hpp

command: bazel cquery  --output=files //bzl:bzl 2>/dev/null
result: bazel-out/k8-fastbuild/bin/bzl/libbzl.a


output for cmake:
/project/main_project/ /project/main_project/bzl /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/bazel_tools~cc_configure_extension~local_config_cc/include /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/boost.assert~/include /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/boost.config~/include /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/boost.container_hash~/include /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/boost.container~/include /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/boost.describe~/include /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/boost.intrusive~/include /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/boost.move~/include /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/boost.mp11~/include /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/boost.static_assert~/include /root/.cache/bazel/_bazel_root/fe5b576dcd0a70e859005dbf05d7e27a/external/boost.type_traits~/include /project/main_project/bazel-out/k8-fastbuild/bin/bzl

bazel end //bzl:bzl

bazel start //:world

Namespace(target='//:world', debug=True, debug_message_limit=1550, args='--config=warnings -c dbg', shell='/bin/bash', no_build=False)
workspace: /project/bzl_world
command: bazel build --config=warnings -c dbg //:world
result: 

command: bazel info --config=warnings -c dbg output_base
result: /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91

command: bazel query 'deps(//:world)'
result: //:include/world/world.hpp
//:src/world.cpp
//:world
@bazel_tools//src/conditions:host_windows
@bazel_tools//src/conditions:host_windows_arm64_constraint
@bazel_tools//src/conditions:host_windows_x64_constraint
@bazel_tools//src/conditions:remote
@bazel_tools//third_party/def_parser:def_parser
@bazel_tools//third_party/def_parser:def_parser.cc
@bazel_tools//third_party/def_parser:def_parser.h
@bazel_tools//third_party/def_parser:def_parser_lib
@bazel_tools//third_party/def_parser:def_parser_main.cc
@bazel_tools//tools/build_defs/build_info:cc_build_info
@bazel_tools//tools/build_defs/build_info/templates:non_volatile_file.h.template
@bazel_tools//tools/build_defs/build_info/templates:redacted_file.h.template
@bazel_tools//tools/build_defs/build_info/templates:volatile_file.h.template
@bazel_tools//tools/build_defs/cc/whitelists/parse_headers_and_layering_check:disabling_parse_headers_and_layering_check_allowed
@bazel_tools//tools/cpp:build_interface_so
@bazel_tools//tools/cpp:current_cc_toolchain
@bazel_tools//tools/cpp:empty_lib
@bazel_tools//tools/cpp:interface_library_builder
@bazel_tools//tools/cpp:link_dynamic_library
@bazel_tools//tools/cpp:link_dynamic_library.sh
@bazel_tools//tools/cpp:link_extra_lib
@bazel_tools//tools/cpp:link_extra_libs
@bazel_tools//tools/cpp:malloc
@bazel_tools//tools/cpp:toolchain
@bazel_tools//tools/cpp:toolchain_type
@bazel_tools//tools/def_parser:def_parser
@bazel_tools//tools/def_parser:def_parser.exe
@bazel_tools//tools/def_parser:def_parser_windows
@bazel_tools//tools/def_parser:n...

command: bazel cquery --config=warnings -c dbg --output=files //:world 2>/dev/null
result: bazel-out/k8-dbg/bin/libworld.a


output for cmake:
/project/bzl_world/include /project/bzl_world/ /project/bzl_world/src /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/bazel_tools~cc_configure_extension~local_config_cc/include /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/boost.assert~/include /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/boost.config~/include /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/boost.container_hash~/include /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/boost.container~/include /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/boost.describe~/include /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/boost.intrusive~/include /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/boost.move~/include /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/boost.mp11~/include /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/boost.static_assert~/include /root/.cache/bazel/_bazel_root/38fa6c732256aafec01ce927d9d05b91/external/boost.type_traits~/include /project/bzl_world/bazel-out/k8-dbg/bin

bazel end //:world"""

        self.maxDiff = None
        self.assertMultiLineEqual(err, expected_err)


if __name__ == "__main__":
    unittest.main()
