load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "bzl",
    srcs = ["bzl.cpp"],
    hdrs = [
        "bzl.hpp",
    ],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        "@boost.container",
    ],
)
