name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: andreiavrammsd/bazel-to-cmake-integration
      options: --user root -v ${{ github.workspace }}:/workspace/:rw

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: ls -l && whoami
