name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.build-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: docker build --cache-from test -t test -f .devcontainer/Dockerfile .

    - name: Run tests
      run: |
        docker run --rm -v $GITHUB_WORKSPACE:/workspace test make test
