name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: .devcontainer/Dockerfile
        push: true
        tags: andreiavrammsd/bazel-to-cmake-integration:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    container:
      image: andreiavrammsd/bazel-to-cmake-integration
      options: --user root -v ${{ github.workspace }}:/workspace/:rw

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: make test
