name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if relevant files changed
      id: changes
      uses: dorny/paths-filter@v2
      with:
        filters: |
          relevant:
            - '.devcontainer/Dockerfile'

    - name: Exit if no relevant changes
      if: steps.changes.outputs.relevant != 'true'
      run: |
        echo "No relevant changes. Skipping build."

    - name: Get branch name slug
      id: slug
      run: |
        echo "slugged_branch=$(echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-')" >> $GITHUB_OUTPUT


    - name: Set Docker tag
      id: docker_tag
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        elif [[ "${{ steps.changes.outputs.relevant }}" == "true" ]]; then
          echo "tag=${{ steps.slug.outputs.slugged_branch }}" >> $GITHUB_OUTPUT
        else
          echo "tag=latest" >> $GITHUB_OUTPUT
        fi

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      if: steps.changes.outputs.relevant == 'true'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      if: steps.changes.outputs.relevant == 'true'

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: .devcontainer/Dockerfile
        push: true
        tags: andreiavrammsd/bazel-to-cmake-integration:${{ steps.docker_tag.outputs.tag }}
      if: steps.changes.outputs.relevant == 'true'

  test:
    runs-on: ubuntu-latest
    needs: build

    container:
      image: andreiavrammsd/bazel-to-cmake-integration:${{ needs.build.outputs.docker_tag }}
      options: --user root -v ${{ github.workspace }}:/workspace/:rw

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: make test
